name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run type-check
      
    - name: Lint
      run: npm run lint
      
    - name: Format check
      run: npm run format -- --check
      
    - name: Setup database
      run: |
        npm run db:generate
        npm run db:migrate
      env:
        DATABASE_URL: file:./test.db
        
    - name: Run unit tests
      run: npm run test:coverage
      env:
        NODE_ENV: test
        DATABASE_URL: file:./test.db
        NEXTAUTH_SECRET: test-secret
        NEXTAUTH_URL: http://localhost:3000
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: file:./test.db
        NEXTAUTH_SECRET: test-secret
        NEXTAUTH_URL: http://localhost:3000

  e2e-tests:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Setup database
      run: |
        npm run db:generate
        npm run db:migrate
      env:
        DATABASE_URL: file:./test.db
        
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        NODE_ENV: test
        DATABASE_URL: file:./test.db
        NEXTAUTH_SECRET: test-secret
        NEXTAUTH_URL: http://localhost:3000
        
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
